=== future-architect/watertower/document-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/Document",
  "definitions": {
    "Document": {
      "required": [
        "unique_key",
        "lang",
        "title",
        "content"
      ],
      "properties": {
        "$comment": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "lang": {
          "type": "string"
        },
        "metadata": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "score": {
          "type": "number"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "unique_key": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== future-architect/watertower/samples/httpstatus/documents/502.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "502",
  "lang": "en",
  "title": "502 Bad Gateway",
  "content": "This error response means that the server, while working as a gateway to get a response needed to handle the request, got an invalid response.",
  "tags": [
    "502"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/428.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "428",
  "lang": "en",
  "title": "428 Precondition Required",
  "content": "The origin server requires the request to be conditional. Intended to prevent the 'lost update' problem, where a client GETs a resource's state, modifies it, and PUTs it back to the server, when meanwhile a third party has modified the state on the server, leading to a conflict.",
  "tags": [
    "428"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/300.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "300",
  "lang": "en",
  "title": "300 Multiple Choice",
  "content": "The request has more than one possible response. The user-agent or user should choose one of them. (There is no standardized way of choosing one of the responses, but HTML links to the possibilities are recommended so the user can pick.)",
  "tags": [
    "300"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/204.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "204",
  "lang": "en",
  "title": "204 No Content",
  "content": "There is no content to send for this request, but the headers may be useful. The user-agent may update its cached headers for this resource with the new ones.",
  "tags": [
    "204"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/507.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "507",
  "lang": "en",
  "title": "507 Insufficient Storage (WebDAV)",
  "content": "The method could not be performed on the resource because the server is unable to store the representation needed to successfully complete the request.",
  "tags": [
    "507"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/421.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "421",
  "lang": "en",
  "title": "421 Misdirected Request",
  "content": "The request was directed at a server that is not able to produce a response. This can be sent by a server that is not configured to produce responses for the combination of scheme and authority that are included in the request URI.",
  "tags": [
    "421"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/202.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "202",
  "lang": "en",
  "title": "202 Accepted",
  "content": "The request has been received but not yet acted upon. It is noncommittal, since there is no way in HTTP to later send an asynchronous response indicating the outcome of the request. It is intended for cases where another process or server handles the request, or for batch processing.",
  "tags": [
    "202"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/431.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "431",
  "lang": "en",
  "title": "431 Request Header Fields Too Large",
  "content": "The server is unwilling to process the request because its header fields are too large. The request MAY be resubmitted after reducing the size of the request header fields.",
  "tags": [
    "431"
  ]
}
