=== future-architect/watertower/document-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/Document",
  "definitions": {
    "Document": {
      "required": [
        "unique_key",
        "lang",
        "title",
        "content"
      ],
      "properties": {
        "$comment": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "lang": {
          "type": "string"
        },
        "metadata": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "score": {
          "type": "number"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "unique_key": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== future-architect/watertower/cmd/httpstatus/documents/201.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "201",
  "lang": "en",
  "title": "201 Created",
  "content": "The request has succeeded and a new resource has been created as a result. This is typically the response sent after POST requests, or some PUT requests.",
  "tags": [
    "201"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/503.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "503",
  "lang": "en",
  "title": "503 Service Unavailable",
  "content": "The server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded. Note that together with this response, a user-friendly page explaining the problem should be sent. This responses should be used for temporary conditions and the Retry-After: HTTP header should, if possible, contain the estimated time before the recovery of the service. The webmaster must also take care about the caching-related headers that are sent along with this response, as these temporary condition responses should usually not be cached.",
  "tags": [
    "503"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/103.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "103",
  "lang": "en",
  "title": "103 Early Hints",
  "content": "This status code is primarily intended to be used with the Link header, letting the user agent start preloading resources while the server prepares a response.",
  "tags": [
    "103"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/408.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "408",
  "lang": "en",
  "title": "408 Request Timeout",
  "content": "This response is sent on an idle connection by some servers, even without any previous request by the client. It means that the server would like to shut down this unused connection. This response is used much more since some browsers, like Chrome, Firefox 27+, or IE9, use HTTP pre-connection mechanisms to speed up surfing. Also note that some servers merely shut down the connection without sending this message.",
  "tags": [
    "408"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/403.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "403",
  "lang": "en",
  "title": "403 Forbidden",
  "content": "The client does not have access rights to the content, i.e. they are unauthorized, so server is rejecting to give proper response. Unlike 401, the client's identity is known to the server.",
  "tags": [
    "403"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/406.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "406",
  "lang": "en",
  "title": "406 Not Acceptable",
  "content": "This response is sent when the web server, after performing server-driven content negotiation, doesn't find any content following the criteria given by the user agent.",
  "tags": [
    "406"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/208.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "208",
  "lang": "en",
  "title": "208 Already Reported (WebDAV)",
  "content": "Used inside a <dav:propstat> response element to avoid enumerating the internal members of multiple bindings to the same collection repeatedly.",
  "tags": [
    "208"
  ]
}

=== future-architect/watertower/cmd/httpstatus/documents/307.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "307",
  "lang": "en",
  "title": "307 Temporary Redirect",
  "content": "The server sends this response to direct the client to get the requested resource at another URI with same method that was used in the prior request. This has the same semantics as the 302 Found HTTP response code, with the exception that the user agent must not change the HTTP method used: If a POST was used in the first request, a POST must be used in the second request.",
  "tags": [
    "307"
  ]
}
