=== future-architect/watertower/document-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/Document",
  "definitions": {
    "Document": {
      "required": [
        "unique_key",
        "lang",
        "title",
        "content"
      ],
      "properties": {
        "$comment": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "lang": {
          "type": "string"
        },
        "metadata": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "score": {
          "type": "number"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "title": {
          "type": "string"
        },
        "unique_key": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== future-architect/watertower/cmd/httpstatus/documents/401.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "401",
  "lang": "en",
  "title": "401 Unauthorized",
  "content": "Although the HTTP standard specifies \"unauthorized\", semantically this response means \"unauthenticated\". That is, the client must authenticate itself to get the requested response.",
  "tags": [
    "401"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/203.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "203",
  "lang": "en",
  "title": "203 Non-Authoritative Information",
  "content": "This response code means the returned meta-information is not exactly the same as available from the origin server, but collected from a local or a third-party copy. This is mostly used for mirrors or backups of another resource. Except for that specific case, 200 OK response should be preferred instead of this status.",
  "tags": [
    "203"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/404.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "404",
  "lang": "en",
  "title": "404 Not Found",
  "content": "The server can not find requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 to hide the existence of a resource from an unauthorized client. This response code is probably the most famous one due to its frequent occurrence on the web.",
  "tags": [
    "404"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/302.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "302",
  "lang": "en",
  "title": "302 Found",
  "content": "This response code means that the URI of requested resource has been changed temporarily. New changes in the URI might be made in the future. Therefore, this same URI should be used by the client in future requests.",
  "tags": [
    "302"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/308.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "308",
  "lang": "en",
  "title": "308 Permanent Redirect",
  "content": "This means that the resource is now permanently located at another URI, specified by the Location: HTTP Response header. This has the same semantics as the 301 Moved Permanently HTTP response code, with the exception that the user agent must not change the HTTP method used: If a POST was used in the first request, a POST must be used in the second request.\nClient error res",
  "tags": [
    "308"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/506.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "506",
  "lang": "en",
  "title": "506 Variant Also Negotiates",
  "content": "The server has an internal configuration error: the chosen variant resource is configured to engage in transparent content negotiation itself, and is therefore not a proper end point in the negotiation process.",
  "tags": [
    "506"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/200.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "200",
  "lang": "en",
  "title": "200 OK",
  "content": "The request has succeeded. The meaning of the success depends on the HTTP method:\nGET: The resource has been fetched and is transmitted in the message body.\nHEAD: The entity headers are in the message body.\nPUT or POST: The resource describing the result of the action is transmitted in the message body.\nTRACE: The message body contains the request message as received by the server",
  "tags": [
    "200"
  ]
}

=== future-architect/watertower/samples/httpstatus/documents/405.json
{
  "$schema": "../../../document-schema.json",
  "unique_key": "405",
  "lang": "en",
  "title": "405 Method Not Allowed",
  "content": "The request method is known by the server but has been disabled and cannot be used. For example, an API may forbid DELETE-ing a resource. The two mandatory methods, GET and HEAD, must never be disabled and should not return this error code.",
  "tags": [
    "405"
  ]
}
